name: Release
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The published name of a single package to release'
        type: choice
        required: false
        options:
          - '@ckohen/discord.js'
          - '@ckohen/brokers'
          - '@ckohen/builders'
          - '@ckohen/collection'
          - '@ckohen/core'
          - 'create-discord-bot'
          - '@ckohen/docgen'
          - '@ckohen/formatters'
          - '@ckohen/next'
          - '@ckohen/proxy'
          - '@ckohen/rest'
          - '@ckohen/util'
          - '@ckohen/voice'
          - '@ckohen/ws'
      exclude:
        description: 'Comma separated list of packages to exclude from release (if not depended upon)'
        required: false
        type: string
        default: '@ckohen/docgen,@ckohen/next'
      dry_run:
        type: boolean
        default: false
jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    if: github.repository_owner == 'ckohen'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'ci/better-release-test'

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmCache

      - name: Build dependencies
        run: pnpm run build

      - name: Release packages
        uses: ./packages/actions/src/releasePackages
        with:
          package: ${{ inputs.package }}
          exclude: ${{ inputs.exclude }}
          dry: ${{ inputs.dry_run }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
